#!/usr/bin/env ruby

require 'rbbt-util'
require 'rbbt/util/simpleopt'

$0 = "rbbt #{$previous_commands*" "} #{ File.basename(__FILE__) }" if $previous_commands

options = SOPT.setup <<EOF

Bootstrap Proteomics pipelines

$ #{$0} [options] <filename.tsv|->

Use - to read from STDIN

-h--help Print this help

EOF
if options[:help]
  if defined? rbbt_usage
    rbbt_usage 
  else
    puts SOPT.doc
  end
  exit 0
end

databases = %w(Appris InterPro UniProt variants)

require 'rbbt/workflow'
Workflow.require_workflow "Proteomics"
databases.each do |database|
 Proteomics.job(:annotate_mi, "BOOTSTRAP", :database  => database, :mutated_isoforms => ["BRCA1:M1652I"] ).exec
end
